name: Maven Build and Publish
on:
  workflow_dispatch: 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build and Publish with Maven
      env:
        JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
        JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      run: |
        mvn clean install
        mvn deploy -Dmaven.deploy.skip=true -Dmaven.test.skip=true -Dmaven.repo.url=http://3.111.42.215:8081/artifactory/webapp/#/artifacts/browse/tree/General/libs-snapshot-local -Dmaven.repo.username=$JFROG_USERNAME -Dmaven.repo.password=$JFROG_PASSWORD
